# Generated by Django 4.1.4 on 2022-12-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('idanimal', models.IntegerField(max_length=9, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.IntegerField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.IntegerField(max_length=9, primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(max_length=9)),
                ('fecha', models.DateField()),
                ('pagado', models.CharField(max_length=1)),
                ('idproducto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='logistica.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Jaula',
            fields=[
                ('idjaula', models.IntegerField(max_length=9, primary_key=True, serialize=False)),
                ('tamanio', models.CharField(max_length=9)),
                ('idanimal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='logistica.animal')),
            ],
        ),
    ]
