# Generated by Django 4.1.4 on 2022-12-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idanimal',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jaula',
            name='idjaula',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idpedido',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idproducto',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
